language: cpp

matrix:
  include:
  - compiler: gcc
    env: COMPILER=g++-4.8
    addons:
      apt:
        sources: ubuntu-toolchain-r-test
        packages:
        - g++-4.8
        - libcppunit-dev

before_install:
  - pip install --user cpp-coveralls

script:
- ./autogen.sh && CXX="$COMPILER" CXXFLAGS="-ftest-coverage -fprofile-arcs" LDFLAGS="-ftest-coverage -fprofile-arcs" ./configure && make -j12
- if [ ! $SKIP_CHECK ]; then make -j12 check; fi

after_success:
  - Rscript -e 'options(covr.gcov = "gcov-4.8");library(covr);coveralls()'
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
